baseURL = "/"
languageCode = "en-us"
title = "Resources"
theme = "ananke"
googleAnalytics = "UA-130028424-1"

SectionPagesMenu = "main"

summarylength = 6

[params]
images = ["/img/logo.png"]
favicon = "favicon.ico?v=kPP08pKEXB"
featured_image = "/img/LandingBanner-lower3.png"
logo = "/img/logo_transparent.png"
custom_css = ["css/custom.css"]
showDates = false
eahubURL = "https://eahub.org"
publicURL = "resources.eahub.org"

[outputs]
home = ["HTML", "JSON"]