[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/contact/"
  to = "https://resources.eagroups.org/support-and-funding-for-groups/connecting-with-cea-and-other-organisers"
